[[solr-indexing-data]]
== Indexing Data

SIREn is fully integrated with the Solr's REST API. You can interact with this API directly to JSON data into the
system, assuming that you have <<solr-setup, installed> and <<solr-configuration, configured>> SIREn in a Solr instance.

For a document to be indexed by SIREn, it needs to have a <<solr-configuration-json-field-type, JSON field type>> in the schema.
Let's assume that we have the following simple Solr schema with two fields, an `id` field that will host the unique
identifier of the JSON document, and a `json` field provided by SIREn to index the JSON data.

[source,markup]
----
<fields>
    <field name="id" type="string" indexed="true" stored="true" required="true" />
    <field name="json" type="json" indexed="true" stored="false"/>
</fields>
----

The JSON data itself needs to be serialized into a string and put as a value for the `json` field. The following command
inserts a JSON document with an identifier of 1 using the Solr XML API:

[source,bash]
----
$ curl http://localhost:8983/solr/collection1/update?commit=true -H "Content-Type: text/xml" --data-binary '
<add>
    <doc>
        <field name="id">1</field>
        <field name="json">
          {
              "ChargeDeviceName": "4c Design Limited, Glasgow (1)",
              "Accessible24Hours": false
          }
        </field>
    </doc>
</add>'
----

When the JSON data is added through the `post.jar` utility provided in the SIREn/Solr distribution, it is essentially
being transformed to a format suitable for consumption by Solr as described above.